### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by SiddeshSambasivam** [SiddeshSambasivam/newscastAPI#17]
## Update the readme: 
- Improve the sentence structuring
- Add references

**Comment by chettriyuvraj** [comment]
Would like to contribute! Referring to the docs for places to improve/simply the framing and add references.

**Comment by SiddeshSambasivam** [comment]
@chettriyuvraj Great! Let me know if you need any clarifications :smiley:

**Comment by chettriyuvraj** [comment]
Have raised a pull request! Do have a look :)

**Comment by chettriyuvraj** [comment]
Thanks! Will look to contribute to the code as well after going through the codebase.
Cheers
