### ISSUE TITLE
Restructure src files

### ISSUE THREAD

**Issue by SiddeshSambasivam** [SiddeshSambasivam/newscastAPI#20]
- Move the `app.py` to the src folder
- Create an `__init__.py` file in the root directory
- Make necessary changes to Procfile (app:app -> src.app:app)

**Comment by Jwright707** [comment]
Hi @SiddeshSambasivam , I would like to tackle this issue 😀

**Comment by SiddeshSambasivam** [comment]
Hey @Jwright707! Let me know if you need any more clarifications 😃
